#!/bin/sh

echo "Commit successful. Pushing mirror to GitHub in the background..."

# Run the push in the background and discard output so it doesn't interrupt your workflow
git push git@github.com:codehia/nixos-config.git -f --mirror

echo "Completed the push to GitHub mirror."
